import { useSyncExternalStore } from "react";

export const LANGUAGES = [
  { code: "pt-BR", label: "Português (Brasil)", nativeLabel: "Português" },
  { code: "en-US", label: "English (United States)", nativeLabel: "English" },
  { code: "es-ES", label: "Español (España)", nativeLabel: "Español" },
] as const;

export type LanguageCode = (typeof LANGUAGES)[number]["code"];
const STORAGE_KEY = "finmonth.language";
const DEFAULT_LANGUAGE: LanguageCode = "pt-BR";

const translations = {
  "pt-BR": {
    settings:"Configurações", settingsDescription:"Gerencie sua conta e as preferências do aplicativo.", profile:"Editar dados do usuário", notifications:"Notificações", language:"Linguagem", languageDescription:"Escolha o idioma usado pelo aplicativo.", themeLight:"Tema claro", themeDark:"Tema escuro", version:"Versão", signOut:"Sair da conta", back:"Voltar", chooseLanguage:"Escolha seu idioma", chooseLanguageDescription:"A preferência fica salva neste dispositivo.", selectedLanguage:"Idioma selecionado",
    home:"Início", bills:"Contas", incomes:"Receitas", savings:"Guardado", finai:"FinAI", finance:"Finanças", myAccount:"Minha conta", openSettings:"Abrir configurações", openNotifications:"Abrir notificações", previousMonth:"Mês anterior", nextMonth:"Próximo mês",
    availableBalance:"Saldo Disponível", positive:"POSITIVO", negative:"NEGATIVO", monthBalance:"Saldo do mês", copyPrevious:"Copiar mês anterior", addBill:"Adicionar conta", addIncome:"Adicionar receita", addSaving:"Adicionar valor guardado", noBills:"Nenhuma conta adicionada neste mês.", noIncomes:"Nenhuma receita adicionada neste mês.", noSavings:"Nenhum valor guardado neste mês.", onlyBills:"Somente as contas adicionadas neste mês.", onlyIncomes:"Somente as receitas adicionadas neste mês.", onlySavings:"Somente os valores guardados neste mês.", savedInMonth:"Guardado no mês",
    edit:"Editar", delete:"Excluir", item:"item", noItems:"Nenhum item cadastrado neste mês.", markPending:"Marcar como pendente", markPaid:"Marcar como paga", paid:"Paga", pending:"Pendente", overdue:"Vencida", due:"Vence", recurring:"Recorrente", day:"dia", days:"dias", today:"hoje", yesterday:"ontem",
    newIncome:"Nova receita", editIncome:"Editar receita", newBill:"Nova conta", editBill:"Editar conta", newSaving:"Novo valor guardado", editSaving:"Editar valor guardado", description:"Descrição", amount:"Valor", amountBrl:"Valor (R$)", incomeDay:"Dia da receita", dueDate:"Vencimento", paidAccount:"Conta paga", recurringAccount:"Recorrente", save:"Salvar", cancel:"Cancelar", saveChanges:"Salvar alterações", saveNewPassword:"Salvar nova senha", selectDay:"Selecione o dia", monthYear:"Mês e ano", salary:"Salário", electricity:"Energia elétrica", emergencyReserve:"Reserva de emergência", manageItem:"Editar item",
    notificationsCount:"aviso", allGood:"Tudo em dia", closeNotifications:"Fechar notificações", noAttention:"Nenhuma conta exige atenção.", notificationHint:"Os avisos aparecem aqui conforme os vencimentos se aproximam.", viewBills:"Ver contas",
    history:"Histórico", allMonths:"Todos os meses", noMonth:"Nenhum mês registrado ainda.", insufficientData:"Sem dados suficientes ainda.", overview:"Visão geral", selectedYearSummary:"Resumo do ano selecionado", selectedMonthSummary:"Resumo do mês selecionado", positiveBalance:"Saldo positivo", negativeBalance:"Saldo negativo", annualComparison:"Comparativo anual", monthlyComparison:"Comparativo mensal", januaryToDecember:"Janeiro a dezembro", lastMonths:"Últimos meses", periodInsights:"Insights do período", previousYearComparison:"Comparação com o ano anterior", previousMonthComparison:"Comparação com o mês anterior", incomeExpense:"Receitas x Despesas", balanceEvolution:"Evolução do saldo", savedPerMonth:"Total guardado por mês", months:"meses", month:"mês", new:"novo",
    completeAnalysis:"Análise completa", monthAnalysis:"Análise do mês", whereMoney:"Onde seu dinheiro está indo", savingsPotential:"Potencial de economia", totalExpenses:"Total de gastos", detailedIncome:"Receitas detalhadas", overdueBills:"Contas atrasadas", recurringBills:"Contas recorrentes", cashFlow:"Fluxo financeiro", dailyAverage:"Média diária", last6Months:"Últimos 6 meses", annualChart:"Gráfico anual", balanceChart:"Evolução do saldo", savingsChart:"Evolução do valor guardado", largestBills:"Maiores contas", monthlyComparisonTitle:"Comparação mensal", pendingBills:"Contas pendentes", paidBills:"Contas pagas", monthlyIncome:"Receitas do mês", monthlyExpenses:"Gastos do mês", savedValue:"Seu valor guardado", financialDataInsufficient:"Dados insuficientes para esta pergunta", canAnalyze:"Posso analisar seus dados", categories:"Categorias financeiras", energyBill:"Conta de energia",
    analysisSuggestion:"Faça uma análise completa", monthQuestion:"Como foi meu mês?", spendingQuestion:"Onde estou gastando mais?", savingQuestion:"Quanto posso guardar?", pendingQuestion:"Quais contas estão pendentes?", finaiHint:"Posso analisar receitas, gastos, contas pagas, pendências, atrasos, recorrências, economia, saldo, fluxo de caixa, médias, comparações, histórico e gráficos. Quando não houver dados suficientes, vou informar isso em vez de estimar ou inventar.", finaiSubtitle:"Sua inteligência financeira no FinMonth.", whatWant:"O que você quer saber?", askMonth:"Pergunte sobre seu mês, compare períodos ou peça um gráfico.", analyzing:"FinAI está analisando seus dados...", dailyQueries:"Consultas hoje", quotaError:"Não foi possível consultar a cota agora. Tente novamente.", quotaReached:"Cota diária atingida. Você poderá usar a FinAI novamente amanhã.", enterQuestion:"Digite sua pergunta...", askFinAi:"Pergunte à FinAI", sendQuestion:"Enviar pergunta", fullHistory:"Ver histórico completo", navigation:"Navegação principal", finaiFootnote:"A FinAI usa os dados financeiros do seu FinMonth para gerar análises.", current:"Atual", previous:"Anterior", total:"Total",
    newPassword:"Criar nova senha", keepPassword:"Deixe em branco para manter", passwordRecovery:"Escolha uma nova senha para recuperar o acesso à sua conta.", confirmPassword:"Confirmar nova senha", minPassword:"Mínimo de 6 caracteres", repeatPassword:"Digite a senha novamente", continue:"Continuar", backToLogin:"Voltar para o login", hidePassword:"Ocultar senha", showPassword:"Mostrar senha", hideNewPassword:"Ocultar nova senha", showNewPassword:"Mostrar nova senha", login:"Entrar", signup:"Criar conta", enterAccount:"Entrar na sua conta", createAccount:"Criar sua conta", financialDataSaved:"Seus dados financeiros ficam salvos e vinculados ao seu usuário.", name:"Nome", email:"E-mail", password:"Senha", yourName:"Seu nome", wait:"Aguarde...", forgotPassword:"Esqueci minha senha", noAccount:"Ainda não tenho conta", hasAccount:"Já tenho uma conta", recoverySent:"Enviamos um link de recuperação para seu e-mail. Verifique também a caixa de spam.", accountCreated:"Conta criada com sucesso.", signupCreated:"Cadastro criado. Confira seu e-mail para confirmar a conta e depois entre.", operationFailed:"Não foi possível concluir a operação.",
    accountNotUpdated:"Não foi possível atualizar sua conta.", accountDeleted:"Excluir sua conta apagará permanentemente seu cadastro e todos os seus dados financeiros. Esta ação não pode ser desfeita. Deseja continuar?", enterName:"Informe seu nome.", sessionExpired:"Sua sessão expirou. Entre novamente.", emailChanged:"Dados salvos. Verifique seu e-mail para confirmar a alteração do endereço.", accountUpdated:"Dados da conta atualizados.", deleteAccount:"Excluir conta", deletingAccount:"Excluindo conta...", notificationsSettings:"Avisos de contas", notificationsDescription:"Configure os avisos de contas próximas, vencendo hoje e atrasadas.", enableNotifications:"Ativar avisos", advanceNotice:"Antecedência", selectAdvance:"Selecione a antecedência", dueToday:"Conta vencendo hoje", overdueNotice:"Conta atrasada", onlyDue:"Somente no vencimento", oneDay:"1 dia antes", twoDays:"2 dias antes", threeDays:"3 dias antes", sevenDays:"7 dias antes", build:"Build", versionInfo:"Informações da versão instalada no dispositivo.", generatedAt:"Gerada em", updateApp:"Atualizar aplicativo", autoUpdateInfo:"O FinMonth verifica automaticamente se existe uma versão publicada mais recente.", newVersion:"Nova versão disponível", updateLatest:"Atualize para usar a versão mais recente do FinMonth.", loadingData:"Carregando seus dados...",
    pageNotFound:"Página não encontrada", pageNotFoundDescription:"A página que você procura não existe ou foi movida.", goHome:"Ir para o início", pageDidNotLoad:"Esta página não carregou", somethingWentWrong:"Algo deu errado. Você pode tentar atualizar ou voltar para o início.", tryAgain:"Tentar novamente",
    historicalDescription:"Consulte receitas, contas e economias de meses anteriores e acompanhe a evolução do seu saldo.", controlFinance:"Controle financeiro pessoal", monthControl:"Controle suas receitas, contas e economias mês a mês",
  },
  "en-US": {
    settings:"Settings", settingsDescription:"Manage your account and app preferences.", profile:"Edit user data", notifications:"Notifications", language:"Language", languageDescription:"Choose the language used by the app.", themeLight:"Light theme", themeDark:"Dark theme", version:"Version", signOut:"Sign out", back:"Back", chooseLanguage:"Choose your language", chooseLanguageDescription:"Your preference is saved on this device.", selectedLanguage:"Selected language",
    home:"Home", bills:"Bills", incomes:"Income", savings:"Saved", finai:"FinAI", finance:"Finances", myAccount:"My account", openSettings:"Open settings", openNotifications:"Open notifications", previousMonth:"Previous month", nextMonth:"Next month",
    availableBalance:"Available Balance", positive:"POSITIVE", negative:"NEGATIVE", monthBalance:"Month balance", copyPrevious:"Copy previous month", addBill:"Add bill", addIncome:"Add income", addSaving:"Add saved amount", noBills:"No bills added this month.", noIncomes:"No income added this month.", noSavings:"No saved amount this month.", onlyBills:"Only bills added this month.", onlyIncomes:"Only income added this month.", onlySavings:"Only saved amounts added this month.", savedInMonth:"Saved this month",
    edit:"Edit", delete:"Delete", item:"item", noItems:"No items registered this month.", markPending:"Mark as pending", markPaid:"Mark as paid", paid:"Paid", pending:"Pending", overdue:"Overdue", due:"Due", recurring:"Recurring", day:"day", days:"days", today:"today", yesterday:"yesterday",
    newIncome:"New income", editIncome:"Edit income", newBill:"New bill", editBill:"Edit bill", newSaving:"New saved amount", editSaving:"Edit saved amount", description:"Description", amount:"Amount", amountBrl:"Amount (BRL)", incomeDay:"Income day", dueDate:"Due date", paidAccount:"Bill paid", recurringAccount:"Recurring", save:"Save", cancel:"Cancel", saveChanges:"Save changes", saveNewPassword:"Save new password", selectDay:"Select the day", monthYear:"Month and year", salary:"Salary", electricity:"Electricity", emergencyReserve:"Emergency fund", manageItem:"Edit item",
    notificationsCount:"notice", allGood:"All caught up", closeNotifications:"Close notifications", noAttention:"No bill needs attention.", notificationHint:"Notices appear here as due dates approach.", viewBills:"View bills",
    history:"History", allMonths:"All months", noMonth:"No month registered yet.", insufficientData:"Not enough data yet.", overview:"Overview", selectedYearSummary:"Selected year summary", selectedMonthSummary:"Selected month summary", positiveBalance:"Positive balance", negativeBalance:"Negative balance", annualComparison:"Annual comparison", monthlyComparison:"Monthly comparison", januaryToDecember:"January to December", lastMonths:"Last months", periodInsights:"Period insights", previousYearComparison:"Comparison with previous year", previousMonthComparison:"Comparison with previous month", incomeExpense:"Income x Expenses", balanceEvolution:"Balance evolution", savedPerMonth:"Total saved per month", months:"months", month:"month", new:"new",
    completeAnalysis:"Complete analysis", monthAnalysis:"Monthly analysis", whereMoney:"Where your money is going", savingsPotential:"Savings potential", totalExpenses:"Total expenses", detailedIncome:"Detailed income", overdueBills:"Overdue bills", recurringBills:"Recurring bills", cashFlow:"Cash flow", dailyAverage:"Daily average", last6Months:"Last 6 months", annualChart:"Annual chart", balanceChart:"Balance evolution", savingsChart:"Saved amount evolution", largestBills:"Largest bills", monthlyComparisonTitle:"Monthly comparison", pendingBills:"Pending bills", paidBills:"Paid bills", monthlyIncome:"Monthly income", monthlyExpenses:"Monthly expenses", savedValue:"Your saved amount", financialDataInsufficient:"Not enough data for this question", canAnalyze:"I can analyze your data", categories:"Financial categories", energyBill:"Energy bill",
    analysisSuggestion:"Do a complete analysis", monthQuestion:"How was my month?", spendingQuestion:"Where am I spending the most?", savingQuestion:"How much can I save?", pendingQuestion:"Which bills are pending?", finaiHint:"I can analyze income, expenses, paid bills, pending bills, overdue bills, recurring bills, savings, balance, cash flow, averages, comparisons, history and charts. When there is not enough data, I will say so instead of estimating or inventing.", finaiSubtitle:"Your financial intelligence in FinMonth.", whatWant:"What do you want to know?", askMonth:"Ask about your month, compare periods, or request a chart.", analyzing:"FinAI is analyzing your data...", dailyQueries:"Queries today", quotaError:"Could not check the quota now. Try again.", quotaReached:"Daily quota reached. You can use FinAI again tomorrow.", enterQuestion:"Type your question...", askFinAi:"Ask FinAI", sendQuestion:"Send question", fullHistory:"View full history", navigation:"Main navigation", finaiFootnote:"FinAI uses your FinMonth financial data to generate analyses.", current:"Current", previous:"Previous", total:"Total",
    newPassword:"Create a new password", keepPassword:"Leave blank to keep current password", passwordRecovery:"Choose a new password to recover access to your account.", confirmPassword:"Confirm new password", minPassword:"At least 6 characters", repeatPassword:"Enter the password again", continue:"Continue", backToLogin:"Back to login", hidePassword:"Hide password", showPassword:"Show password", hideNewPassword:"Hide new password", showNewPassword:"Show new password", login:"Sign in", signup:"Create account", enterAccount:"Sign in to your account", createAccount:"Create your account", financialDataSaved:"Your financial data is saved and linked to your user.", name:"Name", email:"Email", password:"Password", yourName:"Your name", wait:"Please wait...", forgotPassword:"I forgot my password", noAccount:"I don't have an account yet", hasAccount:"I already have an account", recoverySent:"We sent a recovery link to your email. Also check your spam folder.", accountCreated:"Account created successfully.", signupCreated:"Registration created. Check your email to confirm your account and then sign in.", operationFailed:"Could not complete the operation.",
    accountNotUpdated:"Could not update your account.", accountDeleted:"Deleting your account will permanently remove your profile and all financial data. This action cannot be undone. Continue?", enterName:"Enter your name.", sessionExpired:"Your session expired. Please sign in again.", emailChanged:"Data saved. Check your email to confirm the address change.", accountUpdated:"Account data updated.", deleteAccount:"Delete account", deletingAccount:"Deleting account...", notificationsSettings:"Bill alerts", notificationsDescription:"Configure alerts for upcoming, due today, and overdue bills.", enableNotifications:"Enable alerts", advanceNotice:"Advance notice", selectAdvance:"Select advance notice", dueToday:"Bill due today", overdueNotice:"Overdue bill", onlyDue:"On the due date only", oneDay:"1 day before", twoDays:"2 days before", threeDays:"3 days before", sevenDays:"7 days before", build:"Build", versionInfo:"Information about the version installed on the device.", generatedAt:"Generated at", updateApp:"Update app", autoUpdateInfo:"FinMonth automatically checks for a newer published version.", newVersion:"New version available", updateLatest:"Update to use the latest version of FinMonth.", loadingData:"Loading your data...",
    pageNotFound:"Page not found", pageNotFoundDescription:"The page you're looking for doesn't exist or has been moved.", goHome:"Go home", pageDidNotLoad:"This page didn't load", somethingWentWrong:"Something went wrong. You can try refreshing or head back home.", tryAgain:"Try again",
    historicalDescription:"Review income, bills, and savings from previous months and track your balance over time.", controlFinance:"Personal finance control", monthControl:"Track your income, bills, and savings month by month",
  },
  "es-ES": {
    settings:"Configuración", settingsDescription:"Administra tu cuenta y las preferencias de la aplicación.", profile:"Editar datos del usuario", notifications:"Notificaciones", language:"Idioma", languageDescription:"Elige el idioma utilizado por la aplicación.", themeLight:"Tema claro", themeDark:"Tema oscuro", version:"Versión", signOut:"Cerrar sesión", back:"Volver", chooseLanguage:"Elige tu idioma", chooseLanguageDescription:"Tu preferencia se guarda en este dispositivo.", selectedLanguage:"Idioma seleccionado",
    home:"Inicio", bills:"Cuentas", incomes:"Ingresos", savings:"Guardado", finai:"FinAI", finance:"Finanzas", myAccount:"Mi cuenta", openSettings:"Abrir configuración", openNotifications:"Abrir notificaciones", previousMonth:"Mes anterior", nextMonth:"Mes siguiente",
    availableBalance:"Saldo disponible", positive:"POSITIVO", negative:"NEGATIVO", monthBalance:"Saldo del mes", copyPrevious:"Copiar mes anterior", addBill:"Añadir cuenta", addIncome:"Añadir ingreso", addSaving:"Añadir cantidad guardada", noBills:"No hay cuentas añadidas este mes.", noIncomes:"No hay ingresos añadidos este mes.", noSavings:"No hay cantidades guardadas este mes.", onlyBills:"Solo las cuentas añadidas este mes.", onlyIncomes:"Solo los ingresos añadidos este mes.", onlySavings:"Solo las cantidades guardadas este mes.", savedInMonth:"Guardado en el mes",
    edit:"Editar", delete:"Eliminar", item:"elemento", noItems:"No hay elementos registrados este mes.", markPending:"Marcar como pendiente", markPaid:"Marcar como pagada", paid:"Pagada", pending:"Pendiente", overdue:"Vencida", due:"Vence", recurring:"Recurrente", day:"día", days:"días", today:"hoy", yesterday:"ayer",
    newIncome:"Nuevo ingreso", editIncome:"Editar ingreso", newBill:"Nueva cuenta", editBill:"Editar cuenta", newSaving:"Nueva cantidad guardada", editSaving:"Editar cantidad guardada", description:"Descripción", amount:"Importe", amountBrl:"Importe (BRL)", incomeDay:"Día del ingreso", dueDate:"Vencimiento", paidAccount:"Cuenta pagada", recurringAccount:"Recurrente", save:"Guardar", cancel:"Cancelar", saveChanges:"Guardar cambios", saveNewPassword:"Guardar nueva contraseña", selectDay:"Selecciona el día", monthYear:"Mes y año", salary:"Salario", electricity:"Energía eléctrica", emergencyReserve:"Fondo de emergencia", manageItem:"Editar elemento",
    notificationsCount:"aviso", allGood:"Todo al día", closeNotifications:"Cerrar notificaciones", noAttention:"Ninguna cuenta requiere atención.", notificationHint:"Los avisos aparecen aquí cuando se acercan los vencimientos.", viewBills:"Ver cuentas",
    history:"Historial", allMonths:"Todos los meses", noMonth:"Aún no hay meses registrados.", insufficientData:"Aún no hay datos suficientes.", overview:"Resumen", selectedYearSummary:"Resumen del año seleccionado", selectedMonthSummary:"Resumen del mes seleccionado", positiveBalance:"Saldo positivo", negativeBalance:"Saldo negativo", annualComparison:"Comparativa anual", monthlyComparison:"Comparativa mensual", januaryToDecember:"Enero a diciembre", lastMonths:"Últimos meses", periodInsights:"Insights del período", previousYearComparison:"Comparación con el año anterior", previousMonthComparison:"Comparación con el mes anterior", incomeExpense:"Ingresos x Gastos", balanceEvolution:"Evolución del saldo", savedPerMonth:"Total guardado por mes", months:"meses", month:"mes", new:"nuevo",
    completeAnalysis:"Análisis completo", monthAnalysis:"Análisis del mes", whereMoney:"Dónde va tu dinero", savingsPotential:"Potencial de ahorro", totalExpenses:"Total de gastos", detailedIncome:"Ingresos detallados", overdueBills:"Cuentas vencidas", recurringBills:"Cuentas recurrentes", cashFlow:"Flujo financiero", dailyAverage:"Promedio diario", last6Months:"Últimos 6 meses", annualChart:"Gráfico anual", balanceChart:"Evolución del saldo", savingsChart:"Evolución de lo guardado", largestBills:"Cuentas más grandes", monthlyComparisonTitle:"Comparación mensual", pendingBills:"Cuentas pendientes", paidBills:"Cuentas pagadas", monthlyIncome:"Ingresos del mes", monthlyExpenses:"Gastos del mes", savedValue:"Tu cantidad guardada", financialDataInsufficient:"No hay datos suficientes para esta pregunta", canAnalyze:"Puedo analizar tus datos", categories:"Categorías financieras", energyBill:"Cuenta de energía",
    analysisSuggestion:"Haz un análisis completo", monthQuestion:"¿Cómo fue mi mes?", spendingQuestion:"¿Dónde estoy gastando más?", savingQuestion:"¿Cuánto puedo ahorrar?", pendingQuestion:"¿Qué cuentas están pendientes?", finaiHint:"Puedo analizar ingresos, gastos, cuentas pagadas, pendientes, vencimientos, recurrencias, ahorro, saldo, flujo de caja, promedios, comparaciones, historial y gráficos. Cuando no haya datos suficientes, lo indicaré en lugar de estimar o inventar.", finaiSubtitle:"Tu inteligencia financiera en FinMonth.", whatWant:"¿Qué quieres saber?", askMonth:"Pregunta sobre tu mes, compara períodos o solicita un gráfico.", analyzing:"FinAI está analizando tus datos...", dailyQueries:"Consultas de hoy", quotaError:"No se pudo consultar la cuota. Inténtalo de nuevo.", quotaReached:"Se alcanzó la cuota diaria. Podrás usar FinAI de nuevo mañana.", enterQuestion:"Escribe tu pregunta...", askFinAi:"Pregunta a FinAI", sendQuestion:"Enviar pregunta", fullHistory:"Ver historial completo", navigation:"Navegación principal", finaiFootnote:"FinAI utiliza los datos financieros de tu FinMonth para generar análisis.", current:"Actual", previous:"Anterior", total:"Total",
    newPassword:"Crear nueva contraseña", keepPassword:"Déjalo en blanco para mantenerla", passwordRecovery:"Elige una nueva contraseña para recuperar el acceso a tu cuenta.", confirmPassword:"Confirmar nueva contraseña", minPassword:"Mínimo de 6 caracteres", repeatPassword:"Escribe la contraseña de nuevo", continue:"Continuar", backToLogin:"Volver al inicio de sesión", hidePassword:"Ocultar contraseña", showPassword:"Mostrar contraseña", hideNewPassword:"Ocultar nueva contraseña", showNewPassword:"Mostrar nueva contraseña", login:"Iniciar sesión", signup:"Crear cuenta", enterAccount:"Inicia sesión en tu cuenta", createAccount:"Crea tu cuenta", financialDataSaved:"Tus datos financieros se guardan y se vinculan a tu usuario.", name:"Nombre", email:"Correo electrónico", password:"Contraseña", yourName:"Tu nombre", wait:"Espera...", forgotPassword:"Olvidé mi contraseña", noAccount:"Aún no tengo una cuenta", hasAccount:"Ya tengo una cuenta", recoverySent:"Enviamos un enlace de recuperación a tu correo. Revisa también la carpeta de spam.", accountCreated:"Cuenta creada correctamente.", signupCreated:"Registro creado. Revisa tu correo para confirmar la cuenta y luego inicia sesión.", operationFailed:"No se pudo completar la operación.",
    accountNotUpdated:"No se pudo actualizar tu cuenta.", accountDeleted:"Eliminar tu cuenta borrará permanentemente tu perfil y todos tus datos financieros. Esta acción no se puede deshacer. ¿Continuar?", enterName:"Introduce tu nombre.", sessionExpired:"Tu sesión ha caducado. Inicia sesión de nuevo.", emailChanged:"Datos guardados. Revisa tu correo para confirmar el cambio de dirección.", accountUpdated:"Datos de la cuenta actualizados.", deleteAccount:"Eliminar cuenta", deletingAccount:"Eliminando cuenta...", notificationsSettings:"Avisos de cuentas", notificationsDescription:"Configura avisos para cuentas próximas, que vencen hoy y vencidas.", enableNotifications:"Activar avisos", advanceNotice:"Antelación", selectAdvance:"Selecciona la antelación", dueToday:"Cuenta que vence hoy", overdueNotice:"Cuenta vencida", onlyDue:"Solo el día del vencimiento", oneDay:"1 día antes", twoDays:"2 días antes", threeDays:"3 días antes", sevenDays:"7 días antes", build:"Build", versionInfo:"Información de la versión instalada en el dispositivo.", generatedAt:"Generada el", updateApp:"Actualizar aplicación", autoUpdateInfo:"FinMonth comprueba automáticamente si existe una versión publicada más reciente.", newVersion:"Nueva versión disponible", updateLatest:"Actualiza para usar la versión más reciente de FinMonth.", loadingData:"Cargando tus datos...",
    pageNotFound:"Página no encontrada", pageNotFoundDescription:"La página que buscas no existe o se ha movido.", goHome:"Ir al inicio", pageDidNotLoad:"No se pudo cargar esta página", somethingWentWrong:"Algo salió mal. Puedes intentar actualizar o volver al inicio.", tryAgain:"Intentar de nuevo",
    historicalDescription:"Consulta ingresos, cuentas y ahorros de meses anteriores y sigue la evolución de tu saldo.", controlFinance:"Control financiero personal", monthControl:"Controla tus ingresos, cuentas y ahorros mes a mes",
  },
} as const;

export type TranslationKey = keyof (typeof translations)["pt-BR"];

function detectLanguage(): LanguageCode {
  if (typeof navigator === "undefined") return DEFAULT_LANGUAGE;
  const preferred = navigator.language.toLowerCase();
  if (preferred.startsWith("en")) return "en-US";
  if (preferred.startsWith("es")) return "es-ES";
  return DEFAULT_LANGUAGE;
}

let language: LanguageCode = DEFAULT_LANGUAGE;
if (typeof window !== "undefined") {
  try {
    const stored = localStorage.getItem(STORAGE_KEY);
    language = LANGUAGES.some((item) => item.code === stored) ? (stored as LanguageCode) : detectLanguage();
  } catch {
    language = detectLanguage();
  }
}

const listeners = new Set<() => void>();

function emit() {
  listeners.forEach((listener) => listener());
}

export function getCurrentLanguage() {
  return language;
}

export function translate(languageCode: LanguageCode, key: TranslationKey) {
  return translations[languageCode][key];
}

export function setLanguage(next: LanguageCode) {
  language = next;
  try {
    localStorage.setItem(STORAGE_KEY, next);
  } catch {
    /* ignore */
  }
  if (typeof document !== "undefined") document.documentElement.lang = next;
  emit();
}

function subscribe(listener: () => void) {
  listeners.add(listener);
  return () => listeners.delete(listener);
}

const getSnapshot = () => language;
const getServerSnapshot = () => DEFAULT_LANGUAGE;

export function useLanguage() {
  const current = useSyncExternalStore(subscribe, getSnapshot, getServerSnapshot);
  return {
    language: current,
    setLanguage,
    t: (key: TranslationKey) => translations[current][key],
  };
}
